services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    environment:
      SA_PASSWORD: "1234qqqQ"
      ACCEPT_EULA: "Y"
    platform: linux/amd64
    ports:
      - "1433:1433"
